# FROM nginx
# # COPY default.conf /etc/nginx/conf.d/default.conf

# RUN rm /etc/nginx/conf.d/default.conf
# COPY conf /etc/nginx
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]


FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# RUN rm /etc/nginx/conf.d/default.conf
# COPY conf /etc/nginx
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]